name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cppcheck
      run: sudo apt-get update && sudo apt-get install -y cppcheck
    - name: Install Python dependencies
      run: pip install -r python_requirements.txt
    - name: make tests
      run: CFLAGS+=-Werror make tests
