name: Robot CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cppcheck
      run: sudo apt-get update && sudo apt-get install -y cppcheck
    - name: Check cppcheck version
      run: cppcheck --version
    - name: Install Python dependencies
      run: pip install -r python_requirements.txt
    - name: make tests
      run: CFLAGS+=-Werror make tests
  
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
        namespace_name: ${{secrets.NAMESPACE_NAME}}
        container_registry_password: ${{secrets.CONTAINER_REGISTRY_PASSWORD}}
        container_id: ${{secrets.CONTAINER_ID}}
        scaleway_config: ${{secrets.SCALEWAY_CONFIG}}

    steps:
    - uses: actions/checkout@v4
    - name: Install Scaleway CLI
      run: |
        wget https://github.com/scaleway/scaleway-cli/releases/download/v2.42.0/scaleway-cli_2.42.0_linux_amd64 -O /usr/local/bin/scw
        chmod +x /usr/local/bin/scw
    - name: Copy scaleway config file
      run: |
        mkdir -p ~/.config/scw
        printf "%s" "$scaleway_config" > ~/.config/scw/config.yaml
    - name: Build docker image
      run: docker build -f robot.Dockerfile -t robot -t rg.fr-par.scw.cloud/$namespace_name/robot:latest .
    - name: Login to Scaleway's container registry
      run: docker login rg.fr-par.scw.cloud/$namespace_name -u nologin --password-stdin <<< $container_registry_password
    - name: Push docker image
      run: docker push rg.fr-par.scw.cloud/$namespace_name/robot:latest
    - name: Deploy docker image on Scaleway container
      run: scw container container deploy $container_id
